/**
 * Transform API
 * TODO
 *
 * The version of the OpenAPI document: 1.0
 * Contact: someone@maxar.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface AbstractCollectionImageBand
 */
export interface AbstractCollectionImageBand {
    /**
     *
     * @type {boolean}
     * @memberof AbstractCollectionImageBand
     */
    empty?: boolean;
}
/**
 * Check if a given object implements the AbstractCollectionImageBand interface.
 */
export declare function instanceOfAbstractCollectionImageBand(value: object): boolean;
export declare function AbstractCollectionImageBandFromJSON(json: any): AbstractCollectionImageBand;
export declare function AbstractCollectionImageBandFromJSONTyped(json: any, ignoreDiscriminator: boolean): AbstractCollectionImageBand;
export declare function AbstractCollectionImageBandToJSON(value?: AbstractCollectionImageBand | null): any;
