"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Transform API
 * TODO
 *
 * The version of the OpenAPI document: 1.0
 * Contact: someone@maxar.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.AcquisitionScanDirectionToJSON = exports.AcquisitionScanDirectionFromJSONTyped = exports.AcquisitionScanDirectionFromJSON = exports.AcquisitionScanDirection = void 0;
/**
 *
 * @export
 */
exports.AcquisitionScanDirection = {
    Forward: 'Forward',
    Reverse: 'Reverse'
};
function AcquisitionScanDirectionFromJSON(json) {
    return AcquisitionScanDirectionFromJSONTyped(json, false);
}
exports.AcquisitionScanDirectionFromJSON = AcquisitionScanDirectionFromJSON;
function AcquisitionScanDirectionFromJSONTyped(json, ignoreDiscriminator) {
    return json;
}
exports.AcquisitionScanDirectionFromJSONTyped = AcquisitionScanDirectionFromJSONTyped;
function AcquisitionScanDirectionToJSON(value) {
    return value;
}
exports.AcquisitionScanDirectionToJSON = AcquisitionScanDirectionToJSON;
//# sourceMappingURL=AcquisitionScanDirection.js.map