/**
 * Transform API
 * TODO
 *
 * The version of the OpenAPI document: 1.0
 * Contact: someone@maxar.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 */
export declare const AcquisitionScanDirection: {
    readonly Forward: "Forward";
    readonly Reverse: "Reverse";
};
export type AcquisitionScanDirection = typeof AcquisitionScanDirection[keyof typeof AcquisitionScanDirection];
export declare function AcquisitionScanDirectionFromJSON(json: any): AcquisitionScanDirection;
export declare function AcquisitionScanDirectionFromJSONTyped(json: any, ignoreDiscriminator: boolean): AcquisitionScanDirection;
export declare function AcquisitionScanDirectionToJSON(value?: AcquisitionScanDirection | null): any;
