/**
 * Transform API
 * TODO
 *
 * The version of the OpenAPI document: 1.0
 * Contact: someone@maxar.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface Affine
 */
export interface Affine {
    /**
     * The scale factor in the x direction (one of the 6 affine transform parameters).
     * @type {number}
     * @memberof Affine
     */
    scaleX: number;
    /**
     * The scale factor in the y direction (one of the 6 affine transform parameters).
     * @type {number}
     * @memberof Affine
     */
    scaleY: number;
    /**
     * The translation factor in the x direction (one of the 6 affine transform parameters).
     * @type {number}
     * @memberof Affine
     */
    translateX: number;
    /**
     * The translation factor in the y direction (one of the 6 affine transform parameters).
     * @type {number}
     * @memberof Affine
     */
    translateY: number;
    /**
     * The shear factor in the x direction (one of the 6 affine transform parameters).  Note that this parameter is usually 0 since geospatial images do not usually have rotation once rectified to a map projection.
     * @type {number}
     * @memberof Affine
     */
    shearX: number;
    /**
     * The shear factor in the y direction (one of the 6 affine transform parameters).  Note that this parameter is usually 0 since geospatial images do not usually have rotation once rectified to a map projection.
     * @type {number}
     * @memberof Affine
     */
    shearY: number;
}
/**
 * Check if a given object implements the Affine interface.
 */
export declare function instanceOfAffine(value: object): boolean;
export declare function AffineFromJSON(json: any): Affine;
export declare function AffineFromJSONTyped(json: any, ignoreDiscriminator: boolean): Affine;
export declare function AffineToJSON(value?: Affine | null): any;
