"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Transform API
 * TODO
 *
 * The version of the OpenAPI document: 1.0
 * Contact: someone@maxar.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.AffineToJSON = exports.AffineFromJSONTyped = exports.AffineFromJSON = exports.instanceOfAffine = void 0;
/**
 * Check if a given object implements the Affine interface.
 */
function instanceOfAffine(value) {
    let isInstance = true;
    isInstance = isInstance && "scaleX" in value;
    isInstance = isInstance && "scaleY" in value;
    isInstance = isInstance && "translateX" in value;
    isInstance = isInstance && "translateY" in value;
    isInstance = isInstance && "shearX" in value;
    isInstance = isInstance && "shearY" in value;
    return isInstance;
}
exports.instanceOfAffine = instanceOfAffine;
function AffineFromJSON(json) {
    return AffineFromJSONTyped(json, false);
}
exports.AffineFromJSON = AffineFromJSON;
function AffineFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'scaleX': json['scaleX'],
        'scaleY': json['scaleY'],
        'translateX': json['translateX'],
        'translateY': json['translateY'],
        'shearX': json['shearX'],
        'shearY': json['shearY'],
    };
}
exports.AffineFromJSONTyped = AffineFromJSONTyped;
function AffineToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'scaleX': value.scaleX,
        'scaleY': value.scaleY,
        'translateX': value.translateX,
        'translateY': value.translateY,
        'shearX': value.shearX,
        'shearY': value.shearY,
    };
}
exports.AffineToJSON = AffineToJSON;
//# sourceMappingURL=Affine.js.map