"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Transform API
 * TODO
 *
 * The version of the OpenAPI document: 1.0
 * Contact: someone@maxar.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.BandColorInterpretationToJSON = exports.BandColorInterpretationFromJSONTyped = exports.BandColorInterpretationFromJSON = exports.BandColorInterpretation = void 0;
/**
 * Band Color Interpretation
 * @export
 */
exports.BandColorInterpretation = {
    Pan: 'PAN',
    PanWithAlpha: 'PAN_WITH_ALPHA',
    Rgb: 'RGB',
    Rgba: 'RGBA',
    Rgbn: 'RGBN',
    Bgr: 'BGR',
    Bgra: 'BGRA',
    Bgrn: 'BGRN',
    Worldview8Band: 'WORLDVIEW_8_BAND',
    WorldviewSwir: 'WORLDVIEW_SWIR',
    Legion8Band: 'LEGION_8_BAND',
    Unspecified: 'UNSPECIFIED'
};
function BandColorInterpretationFromJSON(json) {
    return BandColorInterpretationFromJSONTyped(json, false);
}
exports.BandColorInterpretationFromJSON = BandColorInterpretationFromJSON;
function BandColorInterpretationFromJSONTyped(json, ignoreDiscriminator) {
    return json;
}
exports.BandColorInterpretationFromJSONTyped = BandColorInterpretationFromJSONTyped;
function BandColorInterpretationToJSON(value) {
    return value;
}
exports.BandColorInterpretationToJSON = BandColorInterpretationToJSON;
//# sourceMappingURL=BandColorInterpretation.js.map