/**
 * Transform API
 * TODO
 *
 * The version of the OpenAPI document: 1.0
 * Contact: someone@maxar.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { AcquisitionScanDirection } from './AcquisitionScanDirection';
import type { CollectBandMetadata } from './CollectBandMetadata';
import type { CollectBandsetMetadata } from './CollectBandsetMetadata';
import type { RangedValue } from './RangedValue';
import type { VehicleName } from './VehicleName';
/**
 *
 * @export
 * @interface CollectMetadata
 */
export interface CollectMetadata {
    /**
     *
     * @type {string}
     * @memberof CollectMetadata
     */
    collectId?: string;
    /**
     *
     * @type {string}
     * @memberof CollectMetadata
     */
    imageBoundsWGS84: string;
    /**
     *
     * @type {VehicleName}
     * @memberof CollectMetadata
     */
    vehicleName?: VehicleName;
    /**
     *
     * @type {string}
     * @memberof CollectMetadata
     */
    vendorName?: string;
    /**
     *
     * @type {string}
     * @memberof CollectMetadata
     */
    vendorDatasetIdentifier?: string;
    /**
     *
     * @type {string}
     * @memberof CollectMetadata
     */
    firstLineTime?: string;
    /**
     *
     * @type {AcquisitionScanDirection}
     * @memberof CollectMetadata
     */
    scanDirection?: AcquisitionScanDirection;
    /**
     *
     * @type {boolean}
     * @memberof CollectMetadata
     */
    dsaOrderMirrorFlag?: boolean;
    /**
     *
     * @type {number}
     * @memberof CollectMetadata
     */
    theoreticalLowDN?: number;
    /**
     *
     * @type {number}
     * @memberof CollectMetadata
     */
    theoreticalHighDN?: number;
    /**
     *
     * @type {RangedValue}
     * @memberof CollectMetadata
     */
    sunAzimuth?: RangedValue;
    /**
     *
     * @type {RangedValue}
     * @memberof CollectMetadata
     */
    sunElevation?: RangedValue;
    /**
     *
     * @type {RangedValue}
     * @memberof CollectMetadata
     */
    satelliteAzimuth?: RangedValue;
    /**
     *
     * @type {RangedValue}
     * @memberof CollectMetadata
     */
    targetAzimuth?: RangedValue;
    /**
     *
     * @type {RangedValue}
     * @memberof CollectMetadata
     */
    satelliteElevation?: RangedValue;
    /**
     *
     * @type {RangedValue}
     * @memberof CollectMetadata
     */
    offNadirAngle?: RangedValue;
    /**
     *
     * @type {number}
     * @memberof CollectMetadata
     */
    cloudCover?: number;
    /**
     *
     * @type {{ [key: string]: CollectBandMetadata; }}
     * @memberof CollectMetadata
     */
    bandMetadata?: {
        [key: string]: CollectBandMetadata;
    };
    /**
     *
     * @type {{ [key: string]: CollectBandsetMetadata; }}
     * @memberof CollectMetadata
     */
    bandsetMetadata?: {
        [key: string]: CollectBandsetMetadata;
    };
}
/**
 * Check if a given object implements the CollectMetadata interface.
 */
export declare function instanceOfCollectMetadata(value: object): boolean;
export declare function CollectMetadataFromJSON(json: any): CollectMetadata;
export declare function CollectMetadataFromJSONTyped(json: any, ignoreDiscriminator: boolean): CollectMetadata;
export declare function CollectMetadataToJSON(value?: CollectMetadata | null): any;
