/**
 * Transform API
 * TODO
 *
 * The version of the OpenAPI document: 1.0
 * Contact: someone@maxar.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { ImageBand } from './ImageBand';
/**
 *
 * @export
 * @interface CollectBandMetadata
 */
export interface CollectBandMetadata {
    /**
     *
     * @type {number}
     * @memberof CollectBandMetadata
     */
    absoluteCalibrationFactor?: number;
    /**
     *
     * @type {number}
     * @memberof CollectBandMetadata
     */
    effectiveBandwidth?: number;
    /**
     *
     * @type {number}
     * @memberof CollectBandMetadata
     */
    spectralMidpoint?: number;
    /**
     *
     * @type {number}
     * @memberof CollectBandMetadata
     */
    tdiLevel?: number;
    /**
     *
     * @type {number}
     * @memberof CollectBandMetadata
     */
    noDataValue?: number;
    /**
     *
     * @type {ImageBand}
     * @memberof CollectBandMetadata
     */
    bandAlias?: ImageBand;
}
/**
 * Check if a given object implements the CollectBandMetadata interface.
 */
export declare function instanceOfCollectBandMetadata(value: object): boolean;
export declare function CollectBandMetadataFromJSON(json: any): CollectBandMetadata;
export declare function CollectBandMetadataFromJSONTyped(json: any, ignoreDiscriminator: boolean): CollectBandMetadata;
export declare function CollectBandMetadataToJSON(value?: CollectBandMetadata | null): any;
