/**
 * Transform API
 * TODO
 *
 * The version of the OpenAPI document: 1.0
 * Contact: someone@maxar.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { OperatorParameterType } from './OperatorParameterType';
/**
 *
 * @export
 * @interface FunctionDescriptorOutputValue
 */
export interface FunctionDescriptorOutputValue {
    /**
     * A description of the parameter.
     * @type {string}
     * @memberof FunctionDescriptorOutputValue
     */
    description?: string;
    /**
     *
     * @type {OperatorParameterType}
     * @memberof FunctionDescriptorOutputValue
     */
    type?: OperatorParameterType;
}
/**
 * Check if a given object implements the FunctionDescriptorOutputValue interface.
 */
export declare function instanceOfFunctionDescriptorOutputValue(value: object): boolean;
export declare function FunctionDescriptorOutputValueFromJSON(json: any): FunctionDescriptorOutputValue;
export declare function FunctionDescriptorOutputValueFromJSONTyped(json: any, ignoreDiscriminator: boolean): FunctionDescriptorOutputValue;
export declare function FunctionDescriptorOutputValueToJSON(value?: FunctionDescriptorOutputValue | null): any;
