"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Transform API
 * TODO
 *
 * The version of the OpenAPI document: 1.0
 * Contact: someone@maxar.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.FunctionDescriptorOutputValueToJSON = exports.FunctionDescriptorOutputValueFromJSONTyped = exports.FunctionDescriptorOutputValueFromJSON = exports.instanceOfFunctionDescriptorOutputValue = void 0;
const runtime_1 = require("../runtime");
const OperatorParameterType_1 = require("./OperatorParameterType");
/**
 * Check if a given object implements the FunctionDescriptorOutputValue interface.
 */
function instanceOfFunctionDescriptorOutputValue(value) {
    let isInstance = true;
    return isInstance;
}
exports.instanceOfFunctionDescriptorOutputValue = instanceOfFunctionDescriptorOutputValue;
function FunctionDescriptorOutputValueFromJSON(json) {
    return FunctionDescriptorOutputValueFromJSONTyped(json, false);
}
exports.FunctionDescriptorOutputValueFromJSON = FunctionDescriptorOutputValueFromJSON;
function FunctionDescriptorOutputValueFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'description': !(0, runtime_1.exists)(json, 'description') ? undefined : json['description'],
        'type': !(0, runtime_1.exists)(json, 'type') ? undefined : (0, OperatorParameterType_1.OperatorParameterTypeFromJSON)(json['type']),
    };
}
exports.FunctionDescriptorOutputValueFromJSONTyped = FunctionDescriptorOutputValueFromJSONTyped;
function FunctionDescriptorOutputValueToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'description': value.description,
        'type': (0, OperatorParameterType_1.OperatorParameterTypeToJSON)(value.type),
    };
}
exports.FunctionDescriptorOutputValueToJSON = FunctionDescriptorOutputValueToJSON;
//# sourceMappingURL=FunctionDescriptorOutputValue.js.map