/**
 * Transform API
 * TODO
 *
 * The version of the OpenAPI document: 1.0
 * Contact: someone@maxar.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { FunctionDescriptorOutputValue } from './FunctionDescriptorOutputValue';
import type { ParameterDescriptor } from './ParameterDescriptor';
/**
 * describes a function
 * @export
 * @interface FunctionDescriptor
 */
export interface FunctionDescriptor {
    /**
     * The name of the function.
     * @type {string}
     * @memberof FunctionDescriptor
     */
    name: string;
    /**
     * A description of what the function does.
     * @type {string}
     * @memberof FunctionDescriptor
     */
    description: string;
    /**
     * The name of the vendor who implemented the operator.
     * @type {string}
     * @memberof FunctionDescriptor
     */
    vendor: string;
    /**
     * The function version.
     * @type {string}
     * @memberof FunctionDescriptor
     */
    version: string;
    /**
     * A map of input parameters used by the function keyed by the name of the parameter.
     * @type {{ [key: string]: ParameterDescriptor; }}
     * @memberof FunctionDescriptor
     */
    parameters: {
        [key: string]: ParameterDescriptor;
    };
    /**
     * A reference to external documentation about the function, if available.
     * @type {string}
     * @memberof FunctionDescriptor
     */
    documentation?: string;
    /**
     *
     * @type {FunctionDescriptorOutputValue}
     * @memberof FunctionDescriptor
     */
    outputValue: FunctionDescriptorOutputValue;
}
/**
 * Check if a given object implements the FunctionDescriptor interface.
 */
export declare function instanceOfFunctionDescriptor(value: object): boolean;
export declare function FunctionDescriptorFromJSON(json: any): FunctionDescriptor;
export declare function FunctionDescriptorFromJSONTyped(json: any, ignoreDiscriminator: boolean): FunctionDescriptor;
export declare function FunctionDescriptorToJSON(value?: FunctionDescriptor | null): any;
