/**
 * Transform API
 * TODO
 *
 * The version of the OpenAPI document: 1.0
 * Contact: someone@maxar.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { HistogramRecord } from './HistogramRecord';
import type { ImageBand } from './ImageBand';
/**
 * A histogram of a rendered image.
 * @export
 * @interface Histogram
 */
export interface Histogram {
    /**
     *
     * @type {Array<ImageBand>}
     * @memberof Histogram
     */
    bands?: Array<ImageBand>;
    /**
     * per band histogram values
     * @type {{ [key: string]: HistogramRecord; }}
     * @memberof Histogram
     */
    histograms?: {
        [key: string]: HistogramRecord;
    };
}
/**
 * Check if a given object implements the Histogram interface.
 */
export declare function instanceOfHistogram(value: object): boolean;
export declare function HistogramFromJSON(json: any): Histogram;
export declare function HistogramFromJSONTyped(json: any, ignoreDiscriminator: boolean): Histogram;
export declare function HistogramToJSON(value?: Histogram | null): any;
