/**
 * Transform API
 * TODO
 *
 * The version of the OpenAPI document: 1.0
 * Contact: someone@maxar.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface HistogramRecord
 */
export interface HistogramRecord {
    /**
     *
     * @type {Array<number>}
     * @memberof HistogramRecord
     */
    histogram: Array<number>;
    /**
     *
     * @type {number}
     * @memberof HistogramRecord
     */
    lowValue: number;
    /**
     *
     * @type {number}
     * @memberof HistogramRecord
     */
    highValue: number;
    /**
     *
     * @type {number}
     * @memberof HistogramRecord
     */
    numBins: number;
}
/**
 * Check if a given object implements the HistogramRecord interface.
 */
export declare function instanceOfHistogramRecord(value: object): boolean;
export declare function HistogramRecordFromJSON(json: any): HistogramRecord;
export declare function HistogramRecordFromJSONTyped(json: any, ignoreDiscriminator: boolean): HistogramRecord;
export declare function HistogramRecordToJSON(value?: HistogramRecord | null): any;
