"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Transform API
 * TODO
 *
 * The version of the OpenAPI document: 1.0
 * Contact: someone@maxar.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.HistogramToJSON = exports.HistogramFromJSONTyped = exports.HistogramFromJSON = exports.instanceOfHistogram = void 0;
const runtime_1 = require("../runtime");
const HistogramRecord_1 = require("./HistogramRecord");
const ImageBand_1 = require("./ImageBand");
/**
 * Check if a given object implements the Histogram interface.
 */
function instanceOfHistogram(value) {
    let isInstance = true;
    return isInstance;
}
exports.instanceOfHistogram = instanceOfHistogram;
function HistogramFromJSON(json) {
    return HistogramFromJSONTyped(json, false);
}
exports.HistogramFromJSON = HistogramFromJSON;
function HistogramFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'bands': !(0, runtime_1.exists)(json, 'bands') ? undefined : (json['bands'].map(ImageBand_1.ImageBandFromJSON)),
        'histograms': !(0, runtime_1.exists)(json, 'histograms') ? undefined : ((0, runtime_1.mapValues)(json['histograms'], HistogramRecord_1.HistogramRecordFromJSON)),
    };
}
exports.HistogramFromJSONTyped = HistogramFromJSONTyped;
function HistogramToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'bands': value.bands === undefined ? undefined : (value.bands.map(ImageBand_1.ImageBandToJSON)),
        'histograms': value.histograms === undefined ? undefined : ((0, runtime_1.mapValues)(value.histograms, HistogramRecord_1.HistogramRecordToJSON)),
    };
}
exports.HistogramToJSON = HistogramToJSON;
//# sourceMappingURL=Histogram.js.map