"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Transform API
 * TODO
 *
 * The version of the OpenAPI document: 1.0
 * Contact: someone@maxar.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.HistogramRecordToJSON = exports.HistogramRecordFromJSONTyped = exports.HistogramRecordFromJSON = exports.instanceOfHistogramRecord = void 0;
/**
 * Check if a given object implements the HistogramRecord interface.
 */
function instanceOfHistogramRecord(value) {
    let isInstance = true;
    isInstance = isInstance && "histogram" in value;
    isInstance = isInstance && "lowValue" in value;
    isInstance = isInstance && "highValue" in value;
    isInstance = isInstance && "numBins" in value;
    return isInstance;
}
exports.instanceOfHistogramRecord = instanceOfHistogramRecord;
function HistogramRecordFromJSON(json) {
    return HistogramRecordFromJSONTyped(json, false);
}
exports.HistogramRecordFromJSON = HistogramRecordFromJSON;
function HistogramRecordFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'histogram': json['histogram'],
        'lowValue': json['lowValue'],
        'highValue': json['highValue'],
        'numBins': json['numBins'],
    };
}
exports.HistogramRecordFromJSONTyped = HistogramRecordFromJSONTyped;
function HistogramRecordToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'histogram': value.histogram,
        'lowValue': value.lowValue,
        'highValue': value.highValue,
        'numBins': value.numBins,
    };
}
exports.HistogramRecordToJSON = HistogramRecordToJSON;
//# sourceMappingURL=HistogramRecord.js.map