/**
 * Transform API
 * TODO
 *
 * The version of the OpenAPI document: 1.0
 * Contact: someone@maxar.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 */
export declare const ImageBand: {
    readonly Pan: "pan";
    readonly Blue: "blue";
    readonly Green: "green";
    readonly Red: "red";
    readonly Nir1: "nir1";
    readonly Coastal: "coastal";
    readonly Yellow: "yellow";
    readonly RedEdge: "red_edge";
    readonly RedEdge1: "red_edge1";
    readonly RedEdge2: "red_edge2";
    readonly Nir2: "nir2";
    readonly S1: "s1";
    readonly S2: "s2";
    readonly S3: "s3";
    readonly S4: "s4";
    readonly S5: "s5";
    readonly S6: "s6";
    readonly S7: "s7";
    readonly S8: "s8";
    readonly Dem: "dem";
    readonly Alpha: "alpha";
    readonly Undefined: "undefined";
};
export type ImageBand = typeof ImageBand[keyof typeof ImageBand];
export declare function ImageBandFromJSON(json: any): ImageBand;
export declare function ImageBandFromJSONTyped(json: any, ignoreDiscriminator: boolean): ImageBand;
export declare function ImageBandToJSON(value?: ImageBand | null): any;
