"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Transform API
 * TODO
 *
 * The version of the OpenAPI document: 1.0
 * Contact: someone@maxar.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ImageStatisticsToJSON = exports.ImageStatisticsFromJSONTyped = exports.ImageStatisticsFromJSON = exports.instanceOfImageStatistics = void 0;
const runtime_1 = require("../runtime");
const ImageStatisticsRecord_1 = require("./ImageStatisticsRecord");
/**
 * Check if a given object implements the ImageStatistics interface.
 */
function instanceOfImageStatistics(value) {
    let isInstance = true;
    return isInstance;
}
exports.instanceOfImageStatistics = instanceOfImageStatistics;
function ImageStatisticsFromJSON(json) {
    return ImageStatisticsFromJSONTyped(json, false);
}
exports.ImageStatisticsFromJSON = ImageStatisticsFromJSON;
function ImageStatisticsFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'statistics': !(0, runtime_1.exists)(json, 'statistics') ? undefined : ((0, runtime_1.mapValues)(json['statistics'], ImageStatisticsRecord_1.ImageStatisticsRecordFromJSON)),
    };
}
exports.ImageStatisticsFromJSONTyped = ImageStatisticsFromJSONTyped;
function ImageStatisticsToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'statistics': value.statistics === undefined ? undefined : ((0, runtime_1.mapValues)(value.statistics, ImageStatisticsRecord_1.ImageStatisticsRecordToJSON)),
    };
}
exports.ImageStatisticsToJSON = ImageStatisticsToJSON;
//# sourceMappingURL=ImageStatistics.js.map