/**
 * Transform API
 * TODO
 *
 * The version of the OpenAPI document: 1.0
 * Contact: someone@maxar.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface ImageStatisticsRecord
 */
export interface ImageStatisticsRecord {
    /**
     *
     * @type {number}
     * @memberof ImageStatisticsRecord
     */
    min: number;
    /**
     *
     * @type {number}
     * @memberof ImageStatisticsRecord
     */
    max: number;
    /**
     *
     * @type {number}
     * @memberof ImageStatisticsRecord
     */
    mean: number;
    /**
     *
     * @type {number}
     * @memberof ImageStatisticsRecord
     */
    standardDeviation: number;
}
/**
 * Check if a given object implements the ImageStatisticsRecord interface.
 */
export declare function instanceOfImageStatisticsRecord(value: object): boolean;
export declare function ImageStatisticsRecordFromJSON(json: any): ImageStatisticsRecord;
export declare function ImageStatisticsRecordFromJSONTyped(json: any, ignoreDiscriminator: boolean): ImageStatisticsRecord;
export declare function ImageStatisticsRecordToJSON(value?: ImageStatisticsRecord | null): any;
