"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Transform API
 * TODO
 *
 * The version of the OpenAPI document: 1.0
 * Contact: someone@maxar.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ImageStatisticsRecordToJSON = exports.ImageStatisticsRecordFromJSONTyped = exports.ImageStatisticsRecordFromJSON = exports.instanceOfImageStatisticsRecord = void 0;
/**
 * Check if a given object implements the ImageStatisticsRecord interface.
 */
function instanceOfImageStatisticsRecord(value) {
    let isInstance = true;
    isInstance = isInstance && "min" in value;
    isInstance = isInstance && "max" in value;
    isInstance = isInstance && "mean" in value;
    isInstance = isInstance && "standardDeviation" in value;
    return isInstance;
}
exports.instanceOfImageStatisticsRecord = instanceOfImageStatisticsRecord;
function ImageStatisticsRecordFromJSON(json) {
    return ImageStatisticsRecordFromJSONTyped(json, false);
}
exports.ImageStatisticsRecordFromJSON = ImageStatisticsRecordFromJSON;
function ImageStatisticsRecordFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'min': json['min'],
        'max': json['max'],
        'mean': json['mean'],
        'standardDeviation': json['standardDeviation'],
    };
}
exports.ImageStatisticsRecordFromJSONTyped = ImageStatisticsRecordFromJSONTyped;
function ImageStatisticsRecordToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'min': value.min,
        'max': value.max,
        'mean': value.mean,
        'standardDeviation': value.standardDeviation,
    };
}
exports.ImageStatisticsRecordToJSON = ImageStatisticsRecordToJSON;
//# sourceMappingURL=ImageStatisticsRecord.js.map