/**
 * Transform API
 * TODO
 *
 * The version of the OpenAPI document: 1.0
 * Contact: someone@maxar.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { SampleDataType } from './SampleDataType';
/**
 *
 * @export
 * @interface ImageMetadata
 */
export interface ImageMetadata {
    /**
     * ImageMetadata Version
     * @type {string}
     * @memberof ImageMetadata
     */
    version: string;
    /**
     * X Index of the first tile
     * @type {number}
     * @memberof ImageMetadata
     */
    minTileX: number;
    /**
     * Y Index of the first tile
     * @type {number}
     * @memberof ImageMetadata
     */
    minTileY: number;
    /**
     * Exclusive x Index of the last tile. (numTilesX=maxTileX-minTileX)
     * @type {number}
     * @memberof ImageMetadata
     */
    maxTileX: number;
    /**
     * Exclusive y Index of the last tile. (numTilesY=maxTileY-minTileY)
     * @type {number}
     * @memberof ImageMetadata
     */
    maxTileY: number;
    /**
     * Number of pixels per tile in the X dimension
     * @type {number}
     * @memberof ImageMetadata
     */
    tileSizeX: number;
    /**
     * Number of pixels per tile in the Y dimension
     * @type {number}
     * @memberof ImageMetadata
     */
    tileSizeY: number;
    /**
     * Number of bands/layers in the image
     * @type {number}
     * @memberof ImageMetadata
     */
    numBands: number;
    /**
     *
     * @type {SampleDataType}
     * @memberof ImageMetadata
     */
    dataType: SampleDataType;
    /**
     * X Index of the first pixel
     * @type {number}
     * @memberof ImageMetadata
     */
    minPixelX: number;
    /**
     * Y Index of the first pixel
     * @type {number}
     * @memberof ImageMetadata
     */
    minPixelY: number;
    /**
     * Exclusive x index of the last pixel.  (width=maxPixelX-minPixelX)
     * @type {number}
     * @memberof ImageMetadata
     */
    maxPixelX: number;
    /**
     * Exclusive y Index of the last pixel. (height=maxPixelY-minPixelY)
     * @type {number}
     * @memberof ImageMetadata
     */
    maxPixelY: number;
    /**
     * The pixel X index of the first pixel in the first tile.
     * @type {number}
     * @memberof ImageMetadata
     */
    tileOffsetX: number;
    /**
     * The pixel Y index of the first pixel in the first tile.
     * @type {number}
     * @memberof ImageMetadata
     */
    tileOffsetY: number;
}
/**
 * Check if a given object implements the ImageMetadata interface.
 */
export declare function instanceOfImageMetadata(value: object): boolean;
export declare function ImageMetadataFromJSON(json: any): ImageMetadata;
export declare function ImageMetadataFromJSONTyped(json: any, ignoreDiscriminator: boolean): ImageMetadata;
export declare function ImageMetadataToJSON(value?: ImageMetadata | null): any;
