/**
 * Transform API
 * TODO
 *
 * The version of the OpenAPI document: 1.0
 * Contact: someone@maxar.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { OperatorParameterType } from './OperatorParameterType';
/**
 * A map of parameters used by the operator keyed by the name of the parameter.
 * @export
 * @interface OperatorParameter
 */
export interface OperatorParameter {
    /**
     * A description of the parameter.
     * @type {string}
     * @memberof OperatorParameter
     */
    description?: string;
    /**
     *
     * @type {OperatorParameterType}
     * @memberof OperatorParameter
     */
    type?: OperatorParameterType;
}
/**
 * Check if a given object implements the OperatorParameter interface.
 */
export declare function instanceOfOperatorParameter(value: object): boolean;
export declare function OperatorParameterFromJSON(json: any): OperatorParameter;
export declare function OperatorParameterFromJSONTyped(json: any, ignoreDiscriminator: boolean): OperatorParameter;
export declare function OperatorParameterToJSON(value?: OperatorParameter | null): any;
