"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Transform API
 * TODO
 *
 * The version of the OpenAPI document: 1.0
 * Contact: someone@maxar.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.OperatorParameterTypeToJSON = exports.OperatorParameterTypeFromJSONTyped = exports.OperatorParameterTypeFromJSON = exports.instanceOfOperatorParameterType = void 0;
const runtime_1 = require("../runtime");
/**
 * Check if a given object implements the OperatorParameterType interface.
 */
function instanceOfOperatorParameterType(value) {
    let isInstance = true;
    return isInstance;
}
exports.instanceOfOperatorParameterType = instanceOfOperatorParameterType;
function OperatorParameterTypeFromJSON(json) {
    return OperatorParameterTypeFromJSONTyped(json, false);
}
exports.OperatorParameterTypeFromJSON = OperatorParameterTypeFromJSON;
function OperatorParameterTypeFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'name': !(0, runtime_1.exists)(json, 'name') ? undefined : json['name'],
        'description': !(0, runtime_1.exists)(json, 'description') ? undefined : json['description'],
        'schema': !(0, runtime_1.exists)(json, 'schema') ? undefined : json['schema'],
    };
}
exports.OperatorParameterTypeFromJSONTyped = OperatorParameterTypeFromJSONTyped;
function OperatorParameterTypeToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'name': value.name,
        'description': value.description,
        'schema': value.schema,
    };
}
exports.OperatorParameterTypeToJSON = OperatorParameterTypeToJSON;
//# sourceMappingURL=OperatorParameterType.js.map