/**
 * Transform API
 * TODO
 *
 * The version of the OpenAPI document: 1.0
 * Contact: someone@maxar.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { OperatorParameterType } from './OperatorParameterType';
/**
 * A description of a parameter used by the operator/function.
 * @export
 * @interface ParameterDescriptor
 */
export interface ParameterDescriptor {
    /**
     * Default value.
     * @type {any}
     * @memberof ParameterDescriptor
     */
    _default?: any | null;
    /**
     * Required or not
     * @type {boolean}
     * @memberof ParameterDescriptor
     */
    required?: boolean;
    /**
     * A description of the parameter.
     * @type {string}
     * @memberof ParameterDescriptor
     */
    description?: string;
    /**
     *
     * @type {OperatorParameterType}
     * @memberof ParameterDescriptor
     */
    type?: OperatorParameterType;
}
/**
 * Check if a given object implements the ParameterDescriptor interface.
 */
export declare function instanceOfParameterDescriptor(value: object): boolean;
export declare function ParameterDescriptorFromJSON(json: any): ParameterDescriptor;
export declare function ParameterDescriptorFromJSONTyped(json: any, ignoreDiscriminator: boolean): ParameterDescriptor;
export declare function ParameterDescriptorToJSON(value?: ParameterDescriptor | null): any;
