"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Transform API
 * TODO
 *
 * The version of the OpenAPI document: 1.0
 * Contact: someone@maxar.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ParameterDescriptorToJSON = exports.ParameterDescriptorFromJSONTyped = exports.ParameterDescriptorFromJSON = exports.instanceOfParameterDescriptor = void 0;
const runtime_1 = require("../runtime");
const OperatorParameterType_1 = require("./OperatorParameterType");
/**
 * Check if a given object implements the ParameterDescriptor interface.
 */
function instanceOfParameterDescriptor(value) {
    let isInstance = true;
    return isInstance;
}
exports.instanceOfParameterDescriptor = instanceOfParameterDescriptor;
function ParameterDescriptorFromJSON(json) {
    return ParameterDescriptorFromJSONTyped(json, false);
}
exports.ParameterDescriptorFromJSON = ParameterDescriptorFromJSON;
function ParameterDescriptorFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        '_default': !(0, runtime_1.exists)(json, 'default') ? undefined : json['default'],
        'required': !(0, runtime_1.exists)(json, 'required') ? undefined : json['required'],
        'description': !(0, runtime_1.exists)(json, 'description') ? undefined : json['description'],
        'type': !(0, runtime_1.exists)(json, 'type') ? undefined : (0, OperatorParameterType_1.OperatorParameterTypeFromJSON)(json['type']),
    };
}
exports.ParameterDescriptorFromJSONTyped = ParameterDescriptorFromJSONTyped;
function ParameterDescriptorToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'default': value._default,
        'required': value.required,
        'description': value.description,
        'type': (0, OperatorParameterType_1.OperatorParameterTypeToJSON)(value.type),
    };
}
exports.ParameterDescriptorToJSON = ParameterDescriptorToJSON;
//# sourceMappingURL=ParameterDescriptor.js.map