/**
 * Transform API
 * TODO
 *
 * The version of the OpenAPI document: 1.0
 * Contact: someone@maxar.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface RangedValue
 */
export interface RangedValue {
    /**
     *
     * @type {number}
     * @memberof RangedValue
     */
    min?: number;
    /**
     *
     * @type {number}
     * @memberof RangedValue
     */
    max?: number;
    /**
     *
     * @type {number}
     * @memberof RangedValue
     */
    mean?: number;
}
/**
 * Check if a given object implements the RangedValue interface.
 */
export declare function instanceOfRangedValue(value: object): boolean;
export declare function RangedValueFromJSON(json: any): RangedValue;
export declare function RangedValueFromJSONTyped(json: any, ignoreDiscriminator: boolean): RangedValue;
export declare function RangedValueToJSON(value?: RangedValue | null): any;
