"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Transform API
 * TODO
 *
 * The version of the OpenAPI document: 1.0
 * Contact: someone@maxar.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.SampleDataTypeToJSON = exports.SampleDataTypeFromJSONTyped = exports.SampleDataTypeFromJSON = exports.SampleDataType = void 0;
/**
 *
 * @export
 */
exports.SampleDataType = {
    Binary: 'BINARY',
    Byte: 'BYTE',
    Short: 'SHORT',
    UnsignedShort: 'UNSIGNED_SHORT',
    Integer: 'INTEGER',
    UnsignedInteger: 'UNSIGNED_INTEGER',
    Long: 'LONG',
    UnsignedLong: 'UNSIGNED_LONG',
    Float: 'FLOAT',
    Double: 'DOUBLE'
};
function SampleDataTypeFromJSON(json) {
    return SampleDataTypeFromJSONTyped(json, false);
}
exports.SampleDataTypeFromJSON = SampleDataTypeFromJSON;
function SampleDataTypeFromJSONTyped(json, ignoreDiscriminator) {
    return json;
}
exports.SampleDataTypeFromJSONTyped = SampleDataTypeFromJSONTyped;
function SampleDataTypeToJSON(value) {
    return value;
}
exports.SampleDataTypeToJSON = SampleDataTypeToJSON;
//# sourceMappingURL=SampleDataType.js.map