/**
 * Transform API
 * TODO
 *
 * The version of the OpenAPI document: 1.0
 * Contact: someone@maxar.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 */
export declare const SpatialTransformType: {
    readonly Epsg: "EPSG";
    readonly Ideal: "IDEAL";
    readonly Undefined: "UNDEFINED";
};
export type SpatialTransformType = typeof SpatialTransformType[keyof typeof SpatialTransformType];
export declare function SpatialTransformTypeFromJSON(json: any): SpatialTransformType;
export declare function SpatialTransformTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): SpatialTransformType;
export declare function SpatialTransformTypeToJSON(value?: SpatialTransformType | null): any;
