/* tslint:disable */
/* eslint-disable */
/**
 * Transform API
 * TODO
 *
 * The version of the OpenAPI document: 1.0
 * Contact: someone@maxar.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const SpatialTransformType = {
    Epsg: 'EPSG',
    Ideal: 'IDEAL',
    Undefined: 'UNDEFINED'
} as const;
export type SpatialTransformType = typeof SpatialTransformType[keyof typeof SpatialTransformType];


export function SpatialTransformTypeFromJSON(json: any): SpatialTransformType {
    return SpatialTransformTypeFromJSONTyped(json, false);
}

export function SpatialTransformTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): SpatialTransformType {
    return json as SpatialTransformType;
}

export function SpatialTransformTypeToJSON(value?: SpatialTransformType | null): any {
    return value as any;
}

