/**
 * Transform API
 * TODO
 *
 * The version of the OpenAPI document: 1.0
 * Contact: someone@maxar.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface StatusType
 */
export interface StatusType {
    /**
     *
     * @type {number}
     * @memberof StatusType
     */
    statusCode?: number;
    /**
     *
     * @type {string}
     * @memberof StatusType
     */
    reasonPhrase?: string;
}
/**
 * Check if a given object implements the StatusType interface.
 */
export declare function instanceOfStatusType(value: object): boolean;
export declare function StatusTypeFromJSON(json: any): StatusType;
export declare function StatusTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): StatusType;
export declare function StatusTypeToJSON(value?: StatusType | null): any;
