/**
 * Transform API
 * TODO
 *
 * The version of the OpenAPI document: 1.0
 * Contact: someone@maxar.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface StoreScriptResponse
 */
export interface StoreScriptResponse {
    /**
     * The id of the script.
     * @type {string}
     * @memberof StoreScriptResponse
     */
    id: string;
}
/**
 * Check if a given object implements the StoreScriptResponse interface.
 */
export declare function instanceOfStoreScriptResponse(value: object): boolean;
export declare function StoreScriptResponseFromJSON(json: any): StoreScriptResponse;
export declare function StoreScriptResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): StoreScriptResponse;
export declare function StoreScriptResponseToJSON(value?: StoreScriptResponse | null): any;
