"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Transform API
 * TODO
 *
 * The version of the OpenAPI document: 1.0
 * Contact: someone@maxar.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.StoreScriptResponseToJSON = exports.StoreScriptResponseFromJSONTyped = exports.StoreScriptResponseFromJSON = exports.instanceOfStoreScriptResponse = void 0;
/**
 * Check if a given object implements the StoreScriptResponse interface.
 */
function instanceOfStoreScriptResponse(value) {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    return isInstance;
}
exports.instanceOfStoreScriptResponse = instanceOfStoreScriptResponse;
function StoreScriptResponseFromJSON(json) {
    return StoreScriptResponseFromJSONTyped(json, false);
}
exports.StoreScriptResponseFromJSON = StoreScriptResponseFromJSON;
function StoreScriptResponseFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'id': json['id'],
    };
}
exports.StoreScriptResponseFromJSONTyped = StoreScriptResponseFromJSONTyped;
function StoreScriptResponseToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'id': value.id,
    };
}
exports.StoreScriptResponseToJSON = StoreScriptResponseToJSON;
//# sourceMappingURL=StoreScriptResponse.js.map