"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Transform API
 * TODO
 *
 * The version of the OpenAPI document: 1.0
 * Contact: someone@maxar.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.TransformProblemToJSON = exports.TransformProblemFromJSONTyped = exports.TransformProblemFromJSON = exports.instanceOfTransformProblem = void 0;
const StatusType_1 = require("./StatusType");
/**
 * Check if a given object implements the TransformProblem interface.
 */
function instanceOfTransformProblem(value) {
    let isInstance = true;
    isInstance = isInstance && "type" in value;
    isInstance = isInstance && "title" in value;
    isInstance = isInstance && "status" in value;
    isInstance = isInstance && "detail" in value;
    isInstance = isInstance && "parameters" in value;
    return isInstance;
}
exports.instanceOfTransformProblem = instanceOfTransformProblem;
function TransformProblemFromJSON(json) {
    return TransformProblemFromJSONTyped(json, false);
}
exports.TransformProblemFromJSON = TransformProblemFromJSON;
function TransformProblemFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'type': json['type'],
        'title': json['title'],
        'status': (0, StatusType_1.StatusTypeFromJSON)(json['status']),
        'detail': json['detail'],
        'parameters': json['parameters'],
    };
}
exports.TransformProblemFromJSONTyped = TransformProblemFromJSONTyped;
function TransformProblemToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'type': value.type,
        'title': value.title,
        'status': (0, StatusType_1.StatusTypeToJSON)(value.status),
        'detail': value.detail,
        'parameters': value.parameters,
    };
}
exports.TransformProblemToJSON = TransformProblemToJSON;
//# sourceMappingURL=TransformProblem.js.map