/**
 * Transform API
 * TODO
 *
 * The version of the OpenAPI document: 1.0
 * Contact: someone@maxar.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface TransformAffine
 */
export interface TransformAffine {
    /**
     * The scale factor in the x direction (one of the 6 affine transform parameters).
     * @type {number}
     * @memberof TransformAffine
     */
    scaleX: number;
    /**
     * The scale factor in the y direction (one of the 6 affine transform parameters).
     * @type {number}
     * @memberof TransformAffine
     */
    scaleY: number;
    /**
     * The translation factor in the x direction (one of the 6 affine transform parameters).
     * @type {number}
     * @memberof TransformAffine
     */
    translateX: number;
    /**
     * The translation factor in the y direction (one of the 6 affine transform parameters).
     * @type {number}
     * @memberof TransformAffine
     */
    translateY: number;
    /**
     * The shear factor in the x direction (one of the 6 affine transform parameters).  Note that this parameter is usually 0 since geospatial images do not usually have rotation once rectified to a map projection.
     * @type {number}
     * @memberof TransformAffine
     */
    shearX: number;
    /**
     * The shear factor in the y direction (one of the 6 affine transform parameters).  Note that this parameter is usually 0 since geospatial images do not usually have rotation once rectified to a map projection.
     * @type {number}
     * @memberof TransformAffine
     */
    shearY: number;
}
/**
 * Check if a given object implements the TransformAffine interface.
 */
export declare function instanceOfTransformAffine(value: object): boolean;
export declare function TransformAffineFromJSON(json: any): TransformAffine;
export declare function TransformAffineFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransformAffine;
export declare function TransformAffineToJSON(value?: TransformAffine | null): any;
