"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Transform API
 * TODO
 *
 * The version of the OpenAPI document: 1.0
 * Contact: someone@maxar.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.TransformAffineToJSON = exports.TransformAffineFromJSONTyped = exports.TransformAffineFromJSON = exports.instanceOfTransformAffine = void 0;
/**
 * Check if a given object implements the TransformAffine interface.
 */
function instanceOfTransformAffine(value) {
    let isInstance = true;
    isInstance = isInstance && "scaleX" in value;
    isInstance = isInstance && "scaleY" in value;
    isInstance = isInstance && "translateX" in value;
    isInstance = isInstance && "translateY" in value;
    isInstance = isInstance && "shearX" in value;
    isInstance = isInstance && "shearY" in value;
    return isInstance;
}
exports.instanceOfTransformAffine = instanceOfTransformAffine;
function TransformAffineFromJSON(json) {
    return TransformAffineFromJSONTyped(json, false);
}
exports.TransformAffineFromJSON = TransformAffineFromJSON;
function TransformAffineFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'scaleX': json['scaleX'],
        'scaleY': json['scaleY'],
        'translateX': json['translateX'],
        'translateY': json['translateY'],
        'shearX': json['shearX'],
        'shearY': json['shearY'],
    };
}
exports.TransformAffineFromJSONTyped = TransformAffineFromJSONTyped;
function TransformAffineToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'scaleX': value.scaleX,
        'scaleY': value.scaleY,
        'translateX': value.translateX,
        'translateY': value.translateY,
        'shearX': value.shearX,
        'shearY': value.shearY,
    };
}
exports.TransformAffineToJSON = TransformAffineToJSON;
//# sourceMappingURL=TransformAffine.js.map