/**
 * Transform API
 * TODO
 *
 * The version of the OpenAPI document: 1.0
 * Contact: someone@maxar.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 * A description of a value input or output from a function or operator.
 * @export
 * @interface ValueDescriptor
 */
export interface ValueDescriptor {
    /**
     * The name of the type.
     * @type {string}
     * @memberof ValueDescriptor
     */
    name?: string;
    /**
     * A description of the type.
     * @type {string}
     * @memberof ValueDescriptor
     */
    description?: string;
    /**
     * The JSONSchema for the type
     * @type {{ [key: string]: any; }}
     * @memberof ValueDescriptor
     */
    schema?: {
        [key: string]: any;
    };
}
/**
 * Check if a given object implements the ValueDescriptor interface.
 */
export declare function instanceOfValueDescriptor(value: object): boolean;
export declare function ValueDescriptorFromJSON(json: any): ValueDescriptor;
export declare function ValueDescriptorFromJSONTyped(json: any, ignoreDiscriminator: boolean): ValueDescriptor;
export declare function ValueDescriptorToJSON(value?: ValueDescriptor | null): any;
