"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Transform API
 * TODO
 *
 * The version of the OpenAPI document: 1.0
 * Contact: someone@maxar.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ValueDescriptorToJSON = exports.ValueDescriptorFromJSONTyped = exports.ValueDescriptorFromJSON = exports.instanceOfValueDescriptor = void 0;
const runtime_1 = require("../runtime");
/**
 * Check if a given object implements the ValueDescriptor interface.
 */
function instanceOfValueDescriptor(value) {
    let isInstance = true;
    return isInstance;
}
exports.instanceOfValueDescriptor = instanceOfValueDescriptor;
function ValueDescriptorFromJSON(json) {
    return ValueDescriptorFromJSONTyped(json, false);
}
exports.ValueDescriptorFromJSON = ValueDescriptorFromJSON;
function ValueDescriptorFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'name': !(0, runtime_1.exists)(json, 'name') ? undefined : json['name'],
        'description': !(0, runtime_1.exists)(json, 'description') ? undefined : json['description'],
        'schema': !(0, runtime_1.exists)(json, 'schema') ? undefined : json['schema'],
    };
}
exports.ValueDescriptorFromJSONTyped = ValueDescriptorFromJSONTyped;
function ValueDescriptorToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'name': value.name,
        'description': value.description,
        'schema': value.schema,
    };
}
exports.ValueDescriptorToJSON = ValueDescriptorToJSON;
//# sourceMappingURL=ValueDescriptor.js.map