"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Transform API
 * TODO
 *
 * The version of the OpenAPI document: 1.0
 * Contact: someone@maxar.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.VehicleNameToJSON = exports.VehicleNameFromJSONTyped = exports.VehicleNameFromJSON = exports.VehicleName = void 0;
/**
 *
 * @export
 */
exports.VehicleName = {
    Wv03: 'WV03',
    Wv02: 'WV02',
    Wv01: 'WV01',
    Qb02: 'QB02',
    Ge01: 'GE01',
    Wv04: 'WV04',
    Ik02: 'IK02',
    Lg01: 'LG01',
    Lg02: 'LG02'
};
function VehicleNameFromJSON(json) {
    return VehicleNameFromJSONTyped(json, false);
}
exports.VehicleNameFromJSON = VehicleNameFromJSON;
function VehicleNameFromJSONTyped(json, ignoreDiscriminator) {
    return json;
}
exports.VehicleNameFromJSONTyped = VehicleNameFromJSONTyped;
function VehicleNameToJSON(value) {
    return value;
}
exports.VehicleNameToJSON = VehicleNameToJSON;
//# sourceMappingURL=VehicleName.js.map