/**
 * Transform API
 * TODO
 *
 * The version of the OpenAPI document: 1.0
 * Contact: someone@maxar.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 */
export declare const VehicleName: {
    readonly Wv03: "WV03";
    readonly Wv02: "WV02";
    readonly Wv01: "WV01";
    readonly Qb02: "QB02";
    readonly Ge01: "GE01";
    readonly Wv04: "WV04";
    readonly Ik02: "IK02";
    readonly Lg01: "LG01";
    readonly Lg02: "LG02";
};
export type VehicleName = typeof VehicleName[keyof typeof VehicleName];
export declare function VehicleNameFromJSON(json: any): VehicleName;
export declare function VehicleNameFromJSONTyped(json: any, ignoreDiscriminator: boolean): VehicleName;
export declare function VehicleNameToJSON(value?: VehicleName | null): any;
